<?php
/** @var Gene_Braintree_Block_Paypal_Info $this */
/** @var array<string, mixed> $_specificInfo */
/** @var string $_label */
/** @var mixed $_value */
?>
<div id="braintree_paypal_logo" style="padding-top: 5px;padding-left: 2px;">
    <img src="/skin/adminhtml/base/default/images/gene/braintree/paypal.png" height="24" alt="<?php echo (string) $this->__('PayPal - Braintree'); ?>" />
</div>

<?php /** @var Mage_Core_Model_Store $store */ ?>
<?php $store = Mage::app()->getStore(); ?>
<?php if ($store->isAdmin() && $this->getMethod()->getCode() == 'braintree_paypal_legacy'): ?>
    <div class="braintree_legacy_order">
        <h4><?php echo (string) $this->__('Legacy Payment'); ?></h4>
        <p><?php echo (string) $this->__('This order was imported from the legacy Braintree extension. The information displayed below maybe incomplete due to information not being provided by the original extension.'); ?></p>
        <p><?php echo (string) $this->__('Certain operations such as credit memos & voiding may not work with this order.'); ?></p>
    </div>
<?php endif; ?>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
    <table>
        <?php foreach ($_specificInfo as $_label => $_value):?>
            <tr>
                <th style="width: 180px"><?php echo (string) $this->escapeHtml($_label)?>:</th>
                <td><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, false)))?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>

<?php echo $this->getChildHtml()?>
