<!-- Gene GooglePay Setup -->
<?php /** @var Gene_Braintree_Block_Googlepay_Setup $this */ ?>
<script type="text/javascript">
    if (typeof vZero !== 'undefined' && typeof vzero === 'undefined') {
        // Start an instance of vZero for the Google Pay instance
        var vzero = new vZero(
            'gene_braintree_creditcard',
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            '<?php echo Mage::getUrl('braintree/checkout/clientToken', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>'
        );
    }
</script>

<script type="text/javascript">
    (function () {
        if (typeof vzero === 'undefined') {
            console.error('Google Pay was unable to initialize as \'vzero\' is undefined in the browser.');
            return;
        }

        // Initialize Google Pay once the integration kit has initialized
        vzero.observeEvent('integration.onInit', function () {
            new vZeroGooglePay(
                false,
                <?php /** @var Mage_Core_Model_Store $store */ ?>
                <?php $store = Mage::app()->getStore(); ?>
                '<?php echo $this->jsQuoteEscape($store->getFrontendName()); ?>',
                this,
                '<?php echo Mage::getUrl('braintree/googlepay/clientToken', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>',
                {
                    environment: '<?php echo $this->jsQuoteEscape($this->getEnvironment()); ?>',
                    merchantAccountId: '<?php echo $this->jsQuoteEscape($this->getGoogleMerchantAccountID()); ?>',
                    currencyCode: '<?php echo $this->jsQuoteEscape($this->getStoreCurrency()); ?>',
                    allowedCardNetworks: <?php echo $this->jsQuoteEscape($this->getAllowedCardNetworks()); ?>
                }
            );
        });
    })();
</script>