<?php
/**
 * Intercept various functions for the multi shipping checkout flow
 * @author Dave Macaulay <braintreesupport@gene.co.uk>
 * @var Gene_Braintree_Block_Js $this
 */
?>
<!-- MULTI SHIPPING BRAINTREE SUPPORT -->
<script type="text/javascript">

    vZeroIntegration.addMethods({

        /**
         * Multi shipping doesn't have ajax states
         **/
        setLoading: function () {
            var btn = document.getElementById('payment-continue');
            btn.setAttribute('disabled','disabled');
            btn.classList.add('loading');
        },
        resetLoading: function () {
            var btn = document.getElementById('payment-continue');
            btn.removeAttribute('disabled');
            btn.classList.remove('loading');
        },

        /**
         * Capture the original submit function
         */
        captureOriginalSubmitFn: function () {
            this._originalSubmitFn = document.getElementById('multishipping-billing-form').submit;
            return true;
        },

        /**
         * Attach an observer to the submit action of the checkout to tokenize the card details
         */
        prepareSubmitObserver: function() {

            // Store a pointer to the vZero integration
            var vzeroIntegration = this;

            // Observe the click event
            document.getElementById('multishipping-billing-form').onsubmit = function braintreeOverride(event) {

                // Stop the event
                event.preventDefault();
                event.stopPropagation();

                var form = document.getElementById('multishipping-billing-form');
                if (vzeroIntegration.shouldInterceptSubmit('creditcard')) {

                    // If everything was a success on the checkout end, let's submit the vZero integration
                    vzeroIntegration.submit('creditcard', function () {
                        return vzeroIntegration._originalSubmitFn.call(form, arguments);
                    });

                } else {
                    return vzeroIntegration._originalSubmitFn.call(form, arguments);
                }

            };

        },

        /**
         * Attach an event to insert the PayPal button on the review step of the checkout
         */
        preparePaymentMethodSwitchObserver: function() {

            // Store a pointer to the vZero integration
            var vzeroIntegration = this;

            // Store the original payment method
            var paymentSwitchOriginal = paymentForm.prototype.switchMethod;

            // Intercept the save function
            paymentForm.prototype.switchMethod = function (method) {

                // Run our method switch function
                vzeroIntegration.paymentMethodSwitch(method);

                // Run the original function
                return paymentSwitchOriginal.apply(this, arguments);
            };

        },

        /**
         * Hide or show the "other" method for both PayPal & Credit Card
         *
         * @param parentElement
         * @param targetElement
         */
        showHideOtherMethod: function (parentElement, targetElement) {

            // Has the user selected other?
            var checkedRadio = document.querySelector(parentElement + ' input:checked[type=radio]');
            var target = document.querySelector(targetElement);

            if (checkedRadio && checkedRadio.value == 'other') {

                if (target) {

                    // Show the credit card form
                    target.style.display = '';

                    // Enable the credit card form all the elements in the credit card form
                    document.querySelectorAll(targetElement + ' input, ' + targetElement + ' select').forEach(function (formElement) {
                        formElement.removeAttribute('disabled');
                    });

                    // Do we need to re-initialize hosted fields?
                    if (this.vzero.hostedFields) {
                        this.initHostedFields();
                    }

                }

            } else if (checkedRadio) {

                if (target) {

                    // Hide the new credit card form
                    target.style.display = 'none';

                    // Disable all the elements in the credit card form
                    document.querySelectorAll(targetElement + ' input, ' + targetElement + ' select').forEach(function (formElement) {
                        formElement.setAttribute('disabled', 'disabled');
                    });

                    // Tear down hosted fields
                    if (this.vzero.hostedFields) {
                        this.vzero.teardownHostedFields();
                        document.getElementById('credit-card-form').classList.add('loading');
                    }

                }

            }
        },

        /**
         * Let the back-end system know the customer is using multi shipping
         */
        getBillingAddress: function () {
            return {
                billing: 'multishipping'
            };
        },

        /**
         * Submit the payment
         */
        submitCheckout: function () {
            return document.getElementById('multishipping-billing-form').submit();
        }

    });

    /**
     * Start a new instance of our integration
     *
     * @type {vZeroIntegration}
     */
    new vZeroIntegration(
        (window.vzero || false),
        (window.vzeroPaypal || false),
        '<div id="paypal-complete"><div id="paypal-container"></div></div>',
        '.buttons-set button#payment-continue',
        true
    );

</script>
<style type="text/css">
    #paypal-label {
        line-height: 44px;
        float: left;
        margin-right: 12px;
    }
    #braintree-paypal-button {
        line-height: initial;
        padding: 0;
        float: left;
    }
    #braintree-paypal-loggedin {
        display: none!important;
    }
    #braintree-paypal-loggedout {
        display: block!important;
    }
</style>