<?php
/**
 * Setup the JavaScript classes with their required fields
 */
/** @var Gene_Braintree_Block_Js $this */
?>
<script type="text/javascript">
    // Only init the vzero class once
    if (typeof vzero === 'undefined') {

        // Pass some data over to vZero integration JS
        var vzero = new vZero(
            'gene_braintree_creditcard',
            false,
            <?php echo $this->is3DEnabled(); ?>,
            true,
            false,
            false,
            '<?php echo Mage::getUrl('braintree/checkout/quoteTotal', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>',
            '<?php echo Mage::getUrl('braintree/checkout/tokenizeCard', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>',
            '<?php echo Mage::getUrl('braintree/checkout/clientToken', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>'
        );

        // Pass the supported card types over to the front-end
        vzero.setSupportedCards('<?php echo $this->getSupportedCardTypes(); ?>');

        // Pass over the merchants Kount credentials
        vzero.setKount(
            '<?php echo $this->getKountEnvironment(); ?>',
            '<?php echo $this->getKountId(); ?>'
        );

        <?php if ($this->isThreeDSpecificCountries()) : ?>
        vzero.setThreeDCountries('<?php echo $this->getThreeDSpecificCountries(); ?>');
        <?php endif; ?>

        vzero.setThreeDFailedAction('<?php echo $this->getThreeDSecureFailedAction(); ?>');

    }
</script>

<div id="three-d-modal" class="hidden">
    <div class="bt-mask"></div>
    <div class="bt-modal-frame">
        <div class="bt-modal-header">
            <div class="header-text"><?php echo $this->__('Authentication'); ?></div>
        </div>
        <div class="bt-modal-body"></div>
    </div>
</div>
