<?php
/** @var Gene_Braintree_Block_Paypal_Info $this */
/** @var array<string, mixed> $_specificInfo */
/** @var string $_label */
/** @var mixed $_value */
?>
<p><strong><?php echo (string) $this->escapeHtml($this->getMethod()->getTitle()) ?></strong></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
    <table>
        <tbody>
        <?php foreach ($_specificInfo as $_label => $_value):
            if($_value):
            ?>
            <tr>
                <th style="text-align: left;font-weight:bold;padding: 3px 0;"><?php echo (string) $this->escapeHtml($_label)?>:</th>
            </tr>
            <tr>
                <td style="padding: 3px 0;"><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, true)))?></td>
            </tr>
        <?php endif;
        endforeach; ?>
        </tbody>
    </table>
<?php endif;?>

<?php echo $this->getChildHtml()?>
