<?php
/** @var Gene_Braintree_Block_Applepay_Express_Setup $this */
/** @var float|int $price */
?>
<?php if (!$this->isEnabled() || !$this->isEnabledPdp()) return; ?>
<?php /** @var Mage_Core_Model_Store $store */ ?>
<?php $store = Mage::app()->getStore(); ?>

<?php
// If we have a grouped product, assume the price as to allow the server side to determine the product price
/** @var Mage_Catalog_Model_Product $product */
$product = $this->getProduct();
$price = $product->getFinalPrice();
if ($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_GROUPED) {
    $price = 1;
}
?>

<script type="text/javascript">
    if (typeof Translator !== 'object' && typeof Translate == 'object') {
        var Translator = new Translate([]);
    }

    if (typeof Translator === 'object') {
        Translator.add({
            "We were unable to complete the request. Please try again.": "<?php echo (string) $this->__('We were unable to complete the request. Please try again.'); ?>"
        })
    }

    (function () {
        mahoOnReady(function() {
            var express = new BraintreeApplePayExpress(
                '<?php echo $this->getToken(); ?>',
                '<?php echo $store->getFrontendName(); ?>',
                '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>',
                'product',
                {
                    clientTokenUrl: '<?php echo $this->getUrl('braintree/applepay/clientToken'); ?>',
                    submitUrl:      '<?php echo $this->getUrl('braintree/applepay/submit') ?>',
                    fetchMethodsUrl:'<?php echo $this->getUrl('braintree/applepay/fetchShippingMethods'); ?>',
                    successUrl:     '<?php echo $this->getUrl('checkout/onepage/success'); ?>'
                },
                {
                    productId:      <?php echo (int) $product->getId(); ?>,
                    virtual:        <?php echo $product->isVirtual() ? 'true' : 'false'; ?>
                }
            );

            // Pass over the quotes grand total for the amount
            express.setAmount('<?php echo number_format($price, 2); ?>');

            // On bundle option changes, update the express amount
            if (typeof window.bundle !== 'undefined') {
                document.addEventListener('bundle:reload-price', function (event) {
                    if (typeof event.detail.priceInclTax !== 'undefined') {
                        express.setAmount(parseFloat(event.detail.priceInclTax).toFixed(2));
                    }
                });
            }

            // Attach our Apple Pay event onto the buttons
            express.attachToButtons(document.querySelectorAll('[data-applepay]'));
        });
    })();
</script>