<?php
/** @var Gene_Braintree_Block_Saved $this */
/** @var array $savedDetails */
/** @var Braintree\CreditCard $savedDetail */
?>
<?php if($savedDetails = $this->getSavedDetails($this->getType())): ?>

<table width="100%">
    <?php /** @var Braintree\CreditCard $savedDetail */
    foreach($savedDetails as $savedDetail): ?>
        <tr>
            <td width="64">
                <img src="<?php echo $this->getSkinUrl('images/gene/braintree/' . Gene_Braintree_Block_Creditcard::getCardIcon($savedDetail->cardType ?? 'card')); ?>" />
            </td>
            <td>
                <span class="payment-method-card-number">
                    <?php echo $savedDetail->bin; ?>******<?php echo $savedDetail->last4; ?>
                </span>
                <span class="payment-method-expiry-date">
                    <em><?php echo (string) $this->__('Expires:'); ?></em> <?php echo $savedDetail->expirationMonth; ?>/<?php echo $savedDetail->expirationYear; ?>
                </span>
            </td>
            <td class="method-options align-right">
                <a href="<?php echo $this->getUrl('*/*/edit', array('id' => $savedDetail->token)); ?>"><?php echo (string) $this->__('Edit'); ?></a>
                <a href="<?php echo $this->getUrl('*/*/remove', array('id' => $savedDetail->token)); ?>" onclick="return confirm('<?php echo (string) $this->__('Are you sure you want to remove this payment method?'); ?>');"><?php echo (string) $this->__('Remove'); ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php endif; ?>
