<?php
/** @var Gene_Braintree_Block_Assets $this */
/** @var string $js */
?>
<!-- Gene_Braintree (<?php echo base64_encode((string) $this->getModuleVersion()); ?>) -->
<?php foreach ($this->getExternalJs() as $js) : ?>
<script src="<?php echo $this->getJsUrl($js); ?>"></script>
<?php endforeach; ?>
<?php foreach ($this->getJs() as $js) : ?>
<script src="<?php echo $this->getJsUrl($js); ?>"></script>
<?php endforeach; ?>