<?php /** @var Gene_Braintree_Block_Adminhtml_Report_Transactions $this */ ?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<?php echo $this->getChildHtml('search'); ?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
