<?php
/** @var Gene_Braintree_Block_Express_Setup $this */
if (!$this->isEnabledPdp()) {
    return;
}
/** @var Mage_Core_Model_Store $store */
$store = Mage::app()->getStore();
$product = $this->getProduct();
?>

<script type="text/javascript">
    if (typeof Translator !== 'object' && typeof Translate == 'object') {
        var Translator = new Translate([]);
    }

    if (typeof Translator === 'object') {
        Translator.add({
            "We were unable to complete the request. Please try again.": "<?php echo (string) $this->__('We were unable to complete the request. Please try again.'); ?>",
            "Checkout with PayPal": "<?php echo (string) $this->__("Checkout with PayPal"); ?>"
        })
    }

    // Override the setStockData function to exclude our PayPal button
    if (typeof Product.ConfigurableSwatches === 'function') {
        var originSetStockData = Product.ConfigurableSwatches.prototype.setStockData;
        Product.ConfigurableSwatches.prototype.setStockData = function () {
            originSetStockData.apply(this, arguments);

            this._E.cartBtn.btn = document.querySelectorAll('.add-to-cart button.button:not([data-paypalexpress]):not(.not-btn-cart)');
        };
    }

    (function () {
        mahoOnReady(function() {
            var express = new BraintreePayPalExpress(
                false,
                '<?php echo addslashes($store->getFrontendName()); ?>',
                '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>',
                'product',
                {
                    clientTokenUrl: '<?php echo Mage::getUrl('braintree/checkout/clientToken', ['_secure' => Mage::app()->getFrontController()->getRequest()->isSecure()]) ?>',
                    authUrl:        '<?php echo $this->getUrl('braintree/express/authorization') ?>',
                    shippingSaveUrl:'<?php echo $this->getUrl('braintree/express/saveShipping') ?>',
                    couponSaveUrl:  '<?php echo $this->getUrl('braintree/express/saveCoupon') ?>',
                    successUrl:     '<?php echo $this->getUrl("checkout/onepage/success"); ?>',
                },
                {
                    locale:         '<?php echo $this->getStoreLocale(); ?>',
                    token:          '<?php echo $this->getToken(); ?>',
                    total:          '<?php echo $product ? $product->getPrice() : ''; ?>',
                    currency:       '<?php echo $this->getStoreCurrency(); ?>',
                    env:            '<?php echo $this->getEnv() ?>',
                    displayName:    '<?php echo addslashes($store->getFrontendName()); ?>',
                    buttonStyle:    <?php echo $this->getStyleConfig('product'); ?>,
                    productId:      <?php echo $product ? (int) $product->getId() : 0; ?>,
                    singleUse:      <?php echo $this->getSingleUse(); ?>,
                    funding:        {<?php echo $this->getFunding(); ?>}
                }
            );
            express.attachToButtons(document.querySelectorAll('[data-paypalexpress]'));

            // Expose the ppExpress object to the window for backwards compatibility
            window.ppExpress = express;
        });
    })();
</script>
